<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>robot_arms_bringup</name>
    <version>0.0.1</version>
    <description>Launch and configuration package for robot arms</description>
    <maintainer email="shashank3199@gmail.com">Shashank Goyal</maintainer>
    <license>Apache License 2.0</license>

    <buildtool_depend>ament_cmake</buildtool_depend>

    <depend>robot_arms_control</depend>
    <depend>launch</depend>
    <depend>launch_ros</depend>
    <depend>ament_index_python</depend>

    <test_depend>ament_lint_auto</test_depend>
    <test_depend>ament_lint_common</test_depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>